services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:  bi_user
      POSTGRES_PASSWORD: bi_pass
      POSTGRES_DB: retail
    ports: ["5432:5432"]
    volumes: [pg_data:/var/lib/postgresql/data]

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

  mcp:
    image: crystaldba/postgres-mcp:0.3.0
    depends_on: [db]
    environment:
      DATABASE_URI: postgresql://bi_user:bi_pass@db:5432/retail
    # ENTRYPOINT = ["postgres-mcp"]  (built into the image)
    command:
      - --access-mode
      - unrestricted          # or restricted in prod
      - --transport
      - sse                   # turns on FastAPI + SSE on :8000
    ports:
      - "4000:8000"           # host 4000 → container 8000

volumes:
  pg_data:
