name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bi_user
          POSTGRES_PASSWORD: bi_pass
          POSTGRES_DB: retail
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U bi_user -d retail"
          --health-interval 5s --health-timeout 5s --health-retries 20

    env:
      POSTGRES_URL: postgresql+psycopg2://bi_user:bi_pass@localhost:5432/retail

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry & deps
        run: |
          python -m pip install -U pip poetry
          poetry install --no-root

      - name: Seed CI data (13 months) via ingest.py
        run: |
          mkdir -p data/raw
          cat > data/raw/ci_seed.csv <<'CSV'
          Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
          A0001,10001,Seed Item,1,2009-12-01 10:00,10.00,1,United Kingdom
          A0002,10001,Seed Item,1,2010-01-01 10:00,10.00,1,United Kingdom
          A0003,10001,Seed Item,1,2010-02-01 10:00,10.00,1,United Kingdom
          A0004,10001,Seed Item,1,2010-03-01 10:00,10.00,1,United Kingdom
          A0005,10001,Seed Item,1,2010-04-01 10:00,10.00,1,United Kingdom
          A0006,10001,Seed Item,1,2010-05-01 10:00,10.00,1,United Kingdom
          A0007,10001,Seed Item,1,2010-06-01 10:00,10.00,1,United Kingdom
          A0008,10001,Seed Item,1,2010-07-01 10:00,10.00,1,United Kingdom
          A0009,10001,Seed Item,1,2010-08-01 10:00,10.00,1,United Kingdom
          A0010,10001,Seed Item,1,2010-09-01 10:00,10.00,1,United Kingdom
          A0011,10001,Seed Item,1,2010-10-01 10:00,10.00,1,United Kingdom
          A0012,10001,Seed Item,1,2010-11-01 10:00,10.00,1,United Kingdom
          A0013,10001,Seed Item,1,2010-12-01 10:00,10.00,1,United Kingdom
          CSV
          poetry run python ingest.py --csv data/raw/ci_seed.csv

      - name: Run tests
        run: poetry run pytest -q
